Add Elapsed Time to Timer
HaikuArchives/HexVexed pull request #16
Opened 2018-12-04 03:08 UTC by claire50

Fixes Issue #12

2018-12-04 04:51 UTC, owenca requested changes
Works for me! Just need minor changes for Haiku's naming conventions.

2018-12-04 04:51 UTC, owenca commented on TimerView.cpp
> +	elapsedTime(0)
```suggestion
	fElapsedTime(0)
```

2018-12-04 04:51 UTC, owenca commented on TimerView.cpp
> +	elapsedTime(0)
From [Haiku Coding Guidelines](https://www.haiku-os.org/development/coding-guidelines/):
![identifiers](https://user-images.githubusercontent.com/6434360/49419505-fcba5080-f73b-11e8-8b12-d27c42512a7e.PNG)

2018-12-04 04:51 UTC, owenca commented on TimerView.cpp
> +	elapsedTime = Elapsed();
```suggestion
	fElapsedTime = Elapsed();
```

2018-12-04 04:51 UTC, owenca commented on TimerView.cpp
> +	bigtime_t elapsed = fRunning ? Elapsed() : elapsedTime;
```suggestion
	bigtime_t elapsed = fRunning ? Elapsed() : fElapsedTime;
```

2018-12-04 04:51 UTC, owenca commented on TimerView.h
> +	int elapsedTime;
```suggestion
	int fElapsedTime;
```

2018-12-08 00:53 UTC, claire50 commented
Hi! I have changed the code a little bit, since I found a simpler way to fix the issue. I was having problems with committing onto GitHub, but I recloned it and changed the code again, so now it works. Thanks!

2018-12-08 03:56 UTC, owenca commented
Thanks for making the fix even better!

2018-12-08 05:18 UTC, merged